// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

namespace bpkg
{
  // pkg_checkout_options
  //

  inline const bool& pkg_checkout_options::
  replace () const
  {
    return this->replace_;
  }
}

// Begin epilogue.
//
//
// End epilogue.
