// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

namespace bpkg
{
  // pkg_clean_options
  //

  inline const bool& pkg_clean_options::
  all () const
  {
    return this->all_;
  }
}

// Begin epilogue.
//
//
// End epilogue.
